sudo: required

services:
  - docker

notifications:
  slack: 
    on_success: never
    on_failure: always
    rooms:
      - oicr:S9k4EowgQv9AnbCfEZHSzCsg

language: java
jdk: 
  - oraclejdk8
python:
  - "2.7"

install: 
  - pip --version  
  - pip install --user cwl-runner

script: 
  - cd launcher
  - mvn -B clean install -DskipITs=false

after_success:
  - mvn -B clean install -DskipITs=false cobertura:cobertura coveralls:report
